behaviors:
  My Behavior:
    trainer_type: sac

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 256
      buffer_size: 63000
      learning_rate: 3.0e-4

      # SAC-specific hyperparameters
      buffer_init_steps: 2000 # policy model update 전 저장. Random하게 움직여서 exploration에 좋음. 일반적으로, 몇 개의 episode는 미리 저장됨.
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 1.0e7
    time_horizon: 64
    summary_freq: 100
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false # sac train speed up
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      rnd:
        strength: 1
        gamma: 0.99
        learning_rate: 3.0e-4
        network_settings:
          normalize: True
          hidden_units: 256
          num_layers: 3
